[tool.poetry]
name = "pco-pro7-automator"
version = "0.1.0"
description = ""
authors = ["trop3n <jasondkimm@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
